# Generated by Django 5.0 on 2023-12-14 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ticket_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=255, null=True, verbose_name='Team Name')),
                ('tableNumber', models.IntegerField(null=True, verbose_name='Table Number')),
                ('round', models.CharField(choices=[('Round 1', 'Round 1'), ('Round 2', 'Round 2'), ('Round 3', 'Round 3'), ('Round 4', 'Round 4')], max_length=255, null=True, verbose_name='Round')),
                ('criteriaA', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], max_length=255, null=True, verbose_name='Criteria A')),
                ('criteriaB', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], max_length=255, null=True, verbose_name='Criteria B')),
                ('criteriaC', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], max_length=255, null=True, verbose_name='Criteria C')),
                ('criteriaD', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], max_length=255, null=True, verbose_name='Criteria D')),
                ('timeCreated', models.DateTimeField(auto_now_add=True, verbose_name='Time Created')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mentor')),
            ],
        ),
    ]
