# Generated by Django 5.0 on 2023-12-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_judgement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='tableNumber',
            field=models.CharField(max_length=10, null=True, verbose_name='Table Number'),
        ),
    ]
