# Generated by Django 5.0 on 2023-12-12 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Venue Name')),
                ('floor', models.IntegerField(null=True, verbose_name='Floor')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255, null=True, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=255, null=True, verbose_name='Last Name')),
                ('organisation', models.CharField(max_length=255, null=True, verbose_name='Organisation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Team Name')),
                ('tableNumber', models.IntegerField(null=True, verbose_name='Table Number')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255, null=True, verbose_name='Issue Description')),
                ('platform', models.CharField(max_length=255, null=True, verbose_name='Platform Information')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Accepted', 'Accepted')], default='Open', max_length=255, null=True, verbose_name='Status')),
                ('timeCreated', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('timeClosed', models.DateTimeField(auto_now_add=True, verbose_name='Closed Time')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mentor')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.team')),
            ],
        ),
    ]
